# Generated by Django 5.0.4 on 2024-04-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FabricaNeeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ativo',
            new_name='active',
        ),
    ]
