# Generated by Django 5.0.4 on 2024-04-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FabricaNeeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_update',
            field=models.DateTimeField(default='2024-04-19 00:00:00:0000'),
            preserve_default=False,
        ),
    ]
