# Generated by Django 5.0.4 on 2024-04-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FabricaNeeds', '0002_rename_ativo_item_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
            },
        ),
    ]
