# Generated by Django 5.0.4 on 2024-04-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FabricaNeeds', '0002_item_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
