# Generated by Django 5.0.4 on 2024-04-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FabricaNeeds', '0003_alter_history_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='item',
        ),
        migrations.AddField(
            model_name='history',
            name='item',
            field=models.ManyToManyField(to='FabricaNeeds.item'),
        ),
    ]
