# Generated by Django 5.0.4 on 2024-04-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FabricaNeeds', '0004_remove_history_item_history_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='item',
            new_name='items',
        ),
    ]
