# Generated by Django 5.0.4 on 2024-05-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FabricaNeeds', '0006_remove_history_items_alter_history_user_itemshistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemshistory',
            options={'verbose_name': 'ItemsHistory', 'verbose_name_plural': 'ItemsHistories'},
        ),
        migrations.AddField(
            model_name='history',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
